name: 'Check PR Title'
description: 'Check if PR title is valid'
inputs:
  org_github_token:
    description: 'Github org token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Checkout repo config
      uses: actions/checkout@v4
      with:
        repository: zapay-pagamentos/repo-config
        token: ${{ inputs.org_github_token }}
        path: repo-config
    - name: Config repo settings
      uses: zapay-pagamentos/zpy-platform-k8s-repo-config-action@main
      with:
        check_pr_title: 'true'
    - uses: zapay-pagamentos/pr-title-checker@main
      with:
        configuration_path: ".github/pr-title-checker-config.json"
        GITHUB_TOKEN: ${{ inputs.org_github_token }}
        use_local_config: true
    - name: Get JSON config
      if: failure()
      id: get_message
      shell: bash
      run: |
          message=$(jq .COMMENT.message $CONFIG_PATH | sed 's/"//g')
          echo "message=$message" >> $GITHUB_OUTPUT
    - uses: zapay-pagamentos/add-pr-comment@master
      if: failure()
      with:
        message: |
          ${{ steps.get_message.outputs.message }}
        repo-token-user-login: github-actions[bot]
      env:
        GITHUB_TOKEN: ${{ inputs.org_github_token }}
